### ISSUE TITLE
drafting unique challenges in educational data

### ISSUE THREAD

**Issue by jrosen48** [jrosen48/data-science-in-education#11]
Hi all, was thinking of outlining / drafting this chapter (chapter 4). If it's okay for me to work on, will share more thoughts and ideas as I begin to make progress.

**Comment by kierisi** [comment]
go for it!

**Comment by jrosen48** [comment]
Hi all, I added a super rough draft [here](https://github.com/jrosen48/data-science-in-education/blob/master/04-unique-challenges.Rmd)

**Comment by jrosen48** [comment]
Hi all, I updated this in this [PR](https://github.com/jrosen48/data-science-in-education/pull/16); still in draft form: needs more examples, references to other resources, etc.
