### ISSUE TITLE
Discussing this burgeoning book in an AERA conference presentation?

### ISSUE THREAD

**Issue by jrosen48** [jrosen48/data-science-in-education#22]
Hi all, I have an opportunity to discuss 'open science' as part of a proposal to present at the [American Educational Research Association (AERA) conference](http://www.aera.net/Events-Meetings/Annual-Meeting/2019-Annual-Meeting-Theme). 

My first thought was to discuss some of my experiences writing this book. I've found it rewarding and perspective-broadening to write this collaboratively and in the open. Though it's not finished (and is very much still in-progress), given the chance, I'd like to share what we've done, but I'd like your thumbs up to do so. If you have thoughts (positive, negative, or other!) about this, please let me know!

Also, if folks would like to join in the presentation (helping with the proposal and, if you like and if it is accepted, presenting at the conference in Toronto in April), I would welcome that (it's not necessary to be at the conference to be involved and at least for AERA many authors aren't able to attend) .

**Comment by restrellado** [comment]
I'd be totally ok with this. I can't make it out to Toronto, but let me know if there's something I can do to support. When will you be presenting? It will be a good way to put more pressure on me to write ahead of the date 👍

**Comment by jrosen48** [comment]
Awesome. Presentation will be mid-late August (if it's accepted). I'll send you the doc r/n.

**Comment by jrosen48** [comment]
See submitted document [here](https://github.com/jrosen48/data-science-in-education/tree/master/sharing-out)

**Comment by jrosen48** [comment]
@restrellado if you have chance can you ping me email address for submission

**Comment by restrellado** [comment]
Hello! You can use ryan.estrellado@gmail.com
